name: Create run matrix of python versions
description: Create a run matrix of python versions for pytest workflow.

inputs:
  coverage-python-version:
    default: ""
    description:
      Python version on which to run the test coverage job. Leave empty to
      skip creating a coverage job.
    required: false
  macos-python-version:
    description:
      Run tests on macOS on a specific version of Python. If left empty, the no
      macOS job will be created.
    required: false
  skipped-python-versions:
    description: Do not run tests on the following supported Python versions.
    required: false

outputs:
  matrix:
    description: A JSON object that can be used for setting `jobs.<job_id>.strategy`.
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - uses: astral-sh/setup-uv@v6
      with:
        enable-cache: false
    - env:
        UV_SYSTEM_PYTHON: 1
      id: set-matrix
      name: Create run matrix in JSON form
      run: |
        delimiter="$(openssl rand -hex 8)"
        echo "matrix<<${delimiter}" >> $GITHUB_OUTPUT
        uv run -p3.13 $GITHUB_ACTION_PATH/main.py \
          --coverage-python-version=${{ inputs.coverage-python-version }} \
          --macos-python-version=${{ inputs.macos-python-version }} \
          --skipped-python-versions='${{ inputs.skipped-python-versions }}' \
          | tee -a $GITHUB_OUTPUT
        echo "${delimiter}" >> $GITHUB_OUTPUT
      shell: bash
