name: Determine task runner
description: Determine which task runner the repository is using.

outputs:
  value:
    description: Short string that describes the task runner. For example "pixi" or "poe".
    value: ${{ steps.task-runner.outputs.value }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: "3.13"
    - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        enable-cache: false
    - env:
        UV_SYSTEM_PYTHON: 1
      id: task-runner
      name: Determine task runner
      run: echo "value=$(uv run -p3.13 $GITHUB_ACTION_PATH/main.py)" | tee -a $GITHUB_OUTPUT
      shell: bash
