tasks:
  - init: pip install -e .[dev]

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addComment: false
    addBadge: false
    addLabel: false

vscode:
  extensions:
    - bungcip.better-toml
    - christian-kohler.path-intellisense
    - eamodio.gitlens
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - github.vscode-github-actions
    - github.vscode-pull-request-github
    - mhutchie.git-graph
    - ms-python.isort
    - ms-python.python
    - redhat.vscode-yaml
    - stkb.rewrap
    - streetsidesoftware.code-spell-checker
    - travisillig.vscode-json-stable-stringify
    - trentrand.git-commit-helper-vscode
    - tyriar.sort-lines
    - yzhang.markdown-all-in-one
