ci:
  autoupdate_commit_msg: "MAINT: autoupdate pre-commit hooks"
  autoupdate_schedule: quarterly
  skip:
    - prettier
    - pyright
    - taplo

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: v0.8.1
    hooks:
      - id: taplo

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
        args:
          - --in-place

  - repo: https://github.com/ComPWA/policy
    rev: 0.3.18
    hooks:
      - id: check-dev-files
        args:
          - --allow-deprecated-workflows
          - --dependabot=update
          - --dev-python-version=3.12
          - --keep-pr-linting
          - --no-gitpod
          - --no-notebooks
          - --no-prettierrc
          - --no-pypi
          - --no-version-branches
          - --repo-name=actions
          - --repo-title=ComPWA actions and shared workflows

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.13.1
    hooks:
      - id: cspell

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
      - id: editorconfig-checker
        name: editorconfig
        alias: ec
        exclude: >-
          (?x)^(
            .*\.py
          )$

  - repo: https://github.com/ComPWA/mirrors-pyright
    rev: v1.1.374
    hooks:
      - id: pyright
