name: Get version of the taplo pre-commit hook
description: >-
  Taplo is written in Rust and its pre-commit hook therefore takes a long time
  to compile. The repository https://github.com/ComPWA/mirrors-taplo provides a
  Docker container that speeds up the hook. This Action runs gets the version
  for the Docker container.

outputs:
  taplo-version:
    description: Version of taplo as determined from .pre-commit-config.yaml
    value: ${{ steps.taplo.outputs.version }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - uses: astral-sh/setup-uv@v3
    - env:
        UV_SYSTEM_PYTHON: 1
      id: taplo
      name: Determine taplo version
      run: |
        echo "version=$(uv run -p3.12 $GITHUB_ACTION_PATH/main.py)" | tee -a $GITHUB_OUTPUT
      shell: bash
