name: Find which hooks are skipped on pre-commit.ci
description: >-
  Find which hooks are skipped on pre-commit.ci and that have to be run on
  GitHub Actions instead.

outputs:
  skipped-hooks:
    description: >-
      Space-separated string of pre-commit hooks that are not run on
      pre-commit.ci. Returns "ALL" if there is no pre.commit.ci config section
      in the `pre-commit-config.yaml`.
    value: ${{ steps.set-hooks.outputs.hooks }}

runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v7
      with:
        cache-python: true
        enable-cache: false
        ignore-empty-workdir: true
    - uses: actions/checkout@v6
      with:
        sparse-checkout: .pre-commit-config.yaml
    - id: set-hooks
      name: Determine skipped hooks
      run: echo "hooks=$(uv run --no-project --python=3.13 $GITHUB_ACTION_PATH/main.py)" | tee -a $GITHUB_OUTPUT
      shell: bash
