name: Find which hooks are skipped on pre-commit.ci
description: >-
  Find which hooks are skipped on pre-commit.ci and that have to be run on
  GitHub Actions instead.

outputs:
  skipped-hooks:
    description: >-
      Space-separated string of pre-commit hooks that are not run on
      pre-commit.ci. Returns "ALL" if there is no pre.commit.ci config section
      in the `pre-commit-config.yaml`.
    value: ${{ steps.set-hooks.outputs.hooks }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - run: python3 -m pip install PyYAML
      shell: bash
    - id: set-hooks
      name: Determine skipped hooks
      run: |
        echo "hooks=$(python3 $GITHUB_ACTION_PATH/main.py)" | tee -a $GITHUB_OUTPUT
      shell: bash
