name: Create run matrix of python versions
description: >-
  Create a run matrix of python versions for pytest workflow.

inputs:
  coverage-python-version:
    default: "3.13"
    description: Python version on which to run the test coverage job.
    required: false
  macos-python-version:
    description: >-
      Run tests on macOS on a specific version of Python. If left empty, the no
      macOS job will be created.
    required: false

outputs:
  matrix:
    description: >-
      A JSON object that can be used for setting `jobs.<job_id>.strategy`.
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - if: hashFiles('pyproject.toml')
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: "3.13"
    - if: hashFiles('pyproject.toml')
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        enable-cache: false
    - env:
        UV_SYSTEM_PYTHON: 1
      id: set-matrix
      if: hashFiles('pyproject.toml')
      name: Create run matrix in JSON form
      run: |
        delimiter="$(openssl rand -hex 8)"
        echo "matrix<<${delimiter}" >> $GITHUB_OUTPUT
        uv run -p3.13 $GITHUB_ACTION_PATH/main.py | tee -a $GITHUB_OUTPUT
        echo "${delimiter}" >> $GITHUB_OUTPUT
      shell: bash
