name: Install local pip package
description: >-
  Install a local package with pip as well as optional dependencies. The action
  automatically detects if there are constraint files under the `.constraints/`
  directory and uses those to constrain the dependencies.

inputs:
  editable:
    description: Install the package in editable mode (`-e` flag).
    required: false
  extras:
    description: Any optional dependencies that the package specifies.
    required: true
  python-version:
    description: Python version used to install the pip packages.
    required: true
  additional-packages:
    default: ""
    description: Any additional packages that need to be installed.
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - uses: actions/cache@v3
      with:
        key: |
          pip-${{ inputs.extras }}-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles('.constraints/py3.*.txt', 'setup.cfg') }}
        restore-keys: |
          pip-${{ inputs.extras }}-${{ runner.os }}-py${{ inputs.python-version }}
        path: ~/.cache/pip/
    - name: Set editable flag
      run: |
        if [[ -z '${{ inputs.editable}}' ]]; then
          echo 'EDITABLE=-e' >> $GITHUB_ENV
        else
          echo 'EDITABLE=' >> $GITHUB_ENV
        fi
      shell: bash
    - run: ${{ format('pip install {0} .[{1}] {2}', env.EDITABLE, inputs.extras, inputs.additional-packages ) }}
      if: hashFiles('.constraints/py3.*.txt') == ''
      shell: bash
    - run: ${{ format('pip install {0} .[{1}] {2} -c .constraints/py{3}.txt', env.EDITABLE, inputs.extras, inputs.additional-packages, inputs.python-version ) }}
      if: hashFiles('.constraints/py3.*.txt') != ''
      shell: bash
