name: Install local pip package
description: >-
  Install a local package with pip as well as optional dependencies. The action
  automatically detects if there are constraint files under the `.constraints/`
  directory and uses those to constrain the dependencies.

inputs:
  extras:
    description: Any optional dependencies that the package specifies.
    required: true
  python-version:
    description: Python version used to install the pip packages.
    required: true
  flags:
    description: Flags that should be passed to `pip install`.
    required: false
  additional-packages:
    default: ""
    description: Any additional packages that need to be installed.
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - uses: actions/cache@v3
      with:
        key: |
          pip-${{ inputs.extras }}-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles('.constraints/py3.*.txt', 'setup.cfg') }}
        restore-keys: |
          pip-${{ inputs.extras }}-${{ runner.os }}-py${{ inputs.python-version }}
        path: ~/.cache/pip/
    - run: ${{ format('pip install .[{0}] {1} {2}', inputs.extras, inputs.additional-packages, inputs.flags ) }}
      if: hashFiles('.constraints/py3.*.txt') == ''
      shell: bash
    - run: ${{ format('pip install .[{0}] {1} {2} -c .constraints/py{3}.txt', inputs.extras, inputs.additional-packages, inputs.flags, inputs.python-version ) }}
      if: hashFiles('.constraints/py3.*.txt') != ''
      shell: bash
