name: Update Jupyter kernels
description: Update the Python version in Jupyter notebooks that have been modified in a PR.

inputs:
  artifact-name:
    description: The name of the artifact to upload
    default: style-changes-jupyter
    required: false
  target-branch:
    description: "The target branch to compare against (default: main)"
    default: ${{ github.event.pull_request.base.ref || 'main' }}
    required: false

runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: false
    - env:
        UV_NO_PROGRESS: 1
      name: Update Jupyter kernels
      run: |
        for notebook in $(git diff --name-only --diff-filter=AMR ${{ inputs.target-branch }} ${{ github.sha }} | grep -E '\.ipynb$'); do
          uv run --directory=$(dirname "$notebook") $GITHUB_ACTION_PATH/main.py "$(basename $notebook)"
        done
      shell: bash
    - run: git diff --color=always
      shell: bash
    - id: updated
      run: |
        if [[ $(git diff --name-only) ]]; then
          delimiter="$(openssl rand -hex 8)"
          echo "notebooks<<${delimiter}" >> $GITHUB_OUTPUT
          echo "$(git diff --name-only)" | tee -a $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT
          mkdir -p .artifacts
          touch .artifacts/keep-root-dir
          exit 1
        fi
      shell: bash
    - if: failure()
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          .artifacts/keep-root-dir
          ${{ steps.updated.outputs.notebooks }}
