on:
  workflow_call:
    inputs:
      gh-pages:
        default: false
        required: false
        type: boolean

jobs:
  linkcheck:
    uses: ./.github/workflows/linkcheck.yml

  docnb:
    uses: ./.github/workflows/docnb.yml

  gh-pages:
    name: Upload to GitHub Pages
    if: inputs.gh-pages && github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs:
      - docnb
      - linkcheck
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/deploy-pages@v1
