on:
  workflow_call:
    inputs:
      hooks:
        description: Pre-commit hooks to run, whitespace-separated
        required: true
        type: string
      python-version:
        default: "3.8"
        required: false
        type: string

jobs:
  style:
    uses: ./.github/workflows/pre-commit.yml
    with:
      hooks: ${{ inputs.hooks }}
      python-version: ${{ inputs.python-version }}
