on:
  workflow_call:
    inputs:
      apt-packages:
        required: false
        type: string
      python-version:
        default: "3.13"
        required: false
        type: string

jobs:
  docnb:
    env:
      EXECUTE_NB: yes
      FORCE_COLOR: yes
      GITHUB_REPO: ${{ github.event.pull_request.head.repo.full_name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      UV_PYTHON: ${{ inputs.python-version }}
    name: Execute and build documentation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
      - name: Fetch Jupyter cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: |
            jupyter-cache-${{ hashFiles('.constraints/py3.*.txt', 'src/**.py', 'uv.lock') }}-${{ hashFiles('docs/**') }}
          restore-keys: |
            jupyter-cache-${{ hashFiles('.constraints/py3.*.txt', 'src/**.py', 'uv.lock') }}
          path: |
            ./docs/_build/.jupyter_cache
      - uses: ComPWA/actions/cache-sympy@99e91bcc486218c7dbbb4f2e0319bfcb028562aa # 4.0.1
      - if: inputs.apt-packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ inputs.apt-packages }}
      - if: hashFiles('**/Project.toml')
        uses: ComPWA/actions/install-julia@99e91bcc486218c7dbbb4f2e0319bfcb028562aa # 4.0.1
        with:
          ijulia: true
      - id: task-runner
        uses: ComPWA/actions/determine-task-runner@99e91bcc486218c7dbbb4f2e0319bfcb028562aa # 4.0.1
      - name: Build documentation and run notebooks (poe)
        if: steps.task-runner.outputs.value == 'poe'
        run: uvx --from poethepoet poe doc
      - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        if: steps.task-runner.outputs.value == 'pixi'
        with:
          cache: true
      - name: Build documentation and run notebooks (Pixi)
        if: steps.task-runner.outputs.value == 'pixi'
        run: pixi run doc
      - if: hashFiles('docs/_build/html')
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: docs/_build/html
