on:
  workflow_call:
    inputs:
      python-version:
        default: "3.8"
        required: false
        type: string

jobs:
  linkcheck:
    name: Check external links
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pip-install
        with:
          additional-packages: tox
          extras: doc
          python-version: ${{ inputs.python-version }}
      - run: tox -e linkcheck
