on:
  workflow_call:
    inputs:
      apt-packages:
        required: false
        type: string
      python-version:
        default: "3.12"
        required: false
        type: string

jobs:
  linkcheck:
    env:
      FORCE_COLOR: yes
      UV_PYTHON: ${{ inputs.python-version }}
    name: Check external links
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
      - if: inputs.apt-packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ inputs.apt-packages }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Run Sphinx linkcheck
        run: |-
          uv tool install --with tox-uv tox
          uv run \
            --group doc \
            --no-dev \
            tox -e linkcheck
