on:
  workflow_call:
    inputs:
      apt-packages:
        required: false
        type: string
      python-version:
        default: "3.12"
        required: false
        type: string

jobs:
  linkcheck:
    name: Check external links
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
      - if: inputs.apt-packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ inputs.apt-packages }}
      - env:
          FORCE_COLOR: yes
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UV_PYTHON_DOWNLOADS: never
          UV_SYSTEM_PYTHON: 1
        name: Run Sphinx linkcheck
        run: >-
          uv run \
            --group doc \
            --no-dev \
            --with tox \
            tox -e linkcheck
