on:
  workflow_call:
    inputs:
      apt-packages:
        required: false
        type: string
      python-version:
        default: "3.12"
        required: false
        type: string

jobs:
  linkcheck:
    name: Check external links
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ComPWA/actions/pip-install@v1
        with:
          additional-packages: tox
          extras: doc
          python-version: ${{ inputs.python-version }}
      - if: inputs.apt-packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ inputs.apt-packages }}
      - run: tox -e linkcheck
        env:
          FORCE_COLOR: yes
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
