on:
  workflow_call:
    inputs:
      apt-packages:
        required: false
        type: string
      python-version:
        default: "3.12"
        required: false
        type: string

jobs:
  linkcheck:
    env:
      FORCE_COLOR: yes
      UV_PYTHON: ${{ inputs.python-version }}
    name: Check external links
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
      - if: inputs.apt-packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ inputs.apt-packages }}
      - id: task-runner
        uses: ComPWA/actions/determine-task-runner@v3
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.task-runner.outputs.value == 'poe'
        name: Run Sphinx linkcheck (poe)
        run: |-
          uv run \
            --group doc \
            --with poethepoet \
            poe linkcheck
      - uses: prefix-dev/setup-pixi@v0.8.14
        if: steps.task-runner.outputs.value == 'pixi'
        with:
          cache: true
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Run Sphinx linkcheck (Pixi)
        if: steps.task-runner.outputs.value == 'pixi'
        run: pixi run linkcheck
