on:
  workflow_call:
    inputs:
      apt-packages:
        required: false
        type: string
      python-version:
        default: "3.13"
        required: false
        type: string

jobs:
  linkcheck:
    env:
      FORCE_COLOR: yes
      UV_PYTHON: ${{ inputs.python-version }}
    name: Check external links
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
      - if: inputs.apt-packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ inputs.apt-packages }}
      - id: task-runner
        uses: ComPWA/actions/determine-task-runner@99e91bcc486218c7dbbb4f2e0319bfcb028562aa # 4.0.1
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.task-runner.outputs.value == 'poe'
        name: Run Sphinx linkcheck (poe)
        run: uvx --from poethepoet poe linkcheck
      - uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347 # v0.10.1
        if: steps.task-runner.outputs.value == 'pixi'
        with:
          cache: true
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Run Sphinx linkcheck (Pixi)
        if: steps.task-runner.outputs.value == 'pixi'
        run: pixi run linkcheck
