name: PR linting
on:
  workflow_call:
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - reopened
      - synchronize
      - unlabeled

jobs:
  check-labels:
    if: github.event.pull_request.state == 'open'
    name: Check labels
    runs-on: ubuntu-24.04
    steps:
      # cspell:ignore agilepathway
      - uses: agilepathway/label-checker@e5e3846bc3669d7444c809a84fcc7d9b7e002f1a # v2.0.5
        with:
          any_of: >-
            🐛 Bug,✨ Feature,⚙️ Enhancement,⚠️ Interface,❗ Behavior,📝 Docs,🔨 Maintenance,⬆️ Lock,🖱️ DX
          none_of: 💥 Epic,💫 Good first issue
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  check-title:
    if: github.event.pull_request.state == 'open'
    name: Check title
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: npm install @compwa/commitlint-config
      - name: Create commitlint config
        run: |
          echo "module.exports = {extends: ['@compwa/commitlint-config']}" > commitlint.config.js
      # cspell:ignore JulienKode
      - uses: JulienKode/pull-request-name-linter-action@8dab22a5f84b07c565ba473f505b0bc5406924dc # v20.5.0
      - if: failure()
        run: >
          echo "::error::Please use a conventional commit message for the pull request title. See https://github.com/ComPWA/compwa.github.io/blob/main/docs/develop.md#commit-conventions for examples."
