on:
  workflow_call:
    inputs:
      python-version:
        default: "3.8"
        required: false
        type: string
    secrets:
      token:
        description: >-
          Personal Access Token for GitHub. This needs to be set as a secret by
          the host repository in order to rerun checks after pushing to a PR.
          The default GITHUB_TOKEN does not suffice for that, see here:
          https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

          This page tells more about creating a PAT:
          https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
        required: false

jobs:
  determine-hooks:
    name: Determine skipped pre-commit hooks
    outputs:
      skipped-hooks: ${{ steps.set-hooks.outputs.skipped-hooks }}
    runs-on: ubuntu-22.04
    steps:
      - id: set-hooks
        uses: ComPWA/actions/get-skipped-pre-commit-hooks@v1

  pre-commit:
    name: Run local pre-commit hooks
    if: needs.determine-hooks.outputs.skipped-hooks != ''
    needs: determine-hooks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.token || secrets.GITHUB_TOKEN }}
      - uses: ComPWA/actions/pip-install@v1
        with:
          editable: "yes"
          extras: sty
          python-version: ${{ inputs.python-version }}
      - name: Fetch pre-commit cache
        uses: actions/cache@v3
        with:
          key: |
            pre-commit-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-py${{ inputs.python-version }}
          path: ~/.cache/pre-commit/
      - if: needs.determine-hooks.outputs.skipped-hooks == 'ALL'
        run: pre-commit run -a --color always
      - if: needs.determine-hooks.outputs.skipped-hooks != 'ALL'
        name: Run pre-commit hooks that don't work on pre-commit.ci
        run: |-
          for hook in ${{ needs.determine-hooks.outputs.skipped-hooks }}; do
            pre-commit run $hook -a --color always
          done
      - if: >
          failure()
          && github.event_name == 'pull_request'
          && github.event.pull_request.head.repo.full_name == github.repository
        name: Push changes
        run: |
          if [[ $(git status -s) ]]; then
            git remote set-url origin https://x-access-token:${{ secrets.token }}@github.com/${{ github.repository }}
            git config user.name "GitHub"
            git config user.email "noreply@github.com"
            git add -A
            git commit -m "MAINT: implement updates from pre-commit hooks"
            git config pull.rebase true
            git pull origin ${{ github.head_ref }}
            git push origin HEAD:${{ github.head_ref }}
          fi
