on:
  workflow_call:
    inputs:
      python-version:
        default: "3.8"
        required: false
        type: string

jobs:
  determine-hooks:
    name: Determine skipped pre-commit hooks
    outputs:
      skipped-hooks: ${{ steps.set-hooks.outputs.skipped-hooks }}
    runs-on: ubuntu-22.04
    steps:
      - id: set-hooks
        uses: ComPWA/actions/get-skipped-pre-commit-hooks@v1

  pre-commit:
    name: Run local pre-commit hooks
    if: needs.determine-hooks.outputs.skipped-hooks != ''
    needs: determine-hooks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ComPWA/actions/pip-install@v1
        with:
          editable: "yes"
          extras: sty
          python-version: ${{ inputs.python-version }}
      - name: Fetch pre-commit cache
        uses: actions/cache@v3
        with:
          key: |
            pre-commit-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-py${{ inputs.python-version }}
          path: ~/.cache/pre-commit/
      - if: needs.determine-hooks.outputs.skipped-hooks == 'ALL'
        run: pre-commit run -a --color always
      - if: needs.determine-hooks.outputs.skipped-hooks != 'ALL'
        name: Run pre-commit hooks that don't work on pre-commit.ci
        run: |-
          for hook in ${{ needs.determine-hooks.outputs.skipped-hooks }}; do
            pre-commit run $hook -a --color always
          done

      - if: failure() && github.event_name == 'pull_request'
        name: Push changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.token }}@github.com/${{ github.repository }}
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git checkout -b ${GITHUB_HEAD_REF}
          if [[ $(git status -s) ]]; then
            git add -A
            git commit -m "MAINT: implement updates from pre-commit hooks"
            git config pull.rebase true
            git pull origin ${GITHUB_HEAD_REF}
            git push origin HEAD:${GITHUB_HEAD_REF}
          fi
