on:
  workflow_call:
    inputs:
      hooks:
        description: Pre-commit hooks to run, whitespace-separated
        required: true
        type: string
      python-version:
        default: "3.8"
        required: false
        type: string

jobs:
  pre-commit:
    name: Run local pre-commit hooks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ComPWA/actions/pip-install@dev
        with:
          extras: sty
          python-version: ${{ inputs.python-version }}
      - name: Fetch pre-commit cache
        uses: actions/cache@v3
        with:
          key: |
            pre-commit-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-py${{ inputs.python-version }}
          path: ~/.cache/pre-commit/
      - name: Run pre-commit hooks that don't work on pre-commit.ci
        run: |-
          for hook in ${{ inputs.hooks }}; do
            pre-commit run $hook -a --color always
          done
