on:
  workflow_call:
    inputs:
      python-version:
        default: "3.8"
        required: false
        type: string
    secrets:
      token:
        description: >-
          Personal Access Token for GitHub. This needs to be set as a secret by
          the host repository in order to rerun checks after pushing to a PR.
          The default GITHUB_TOKEN does not suffice for that, see here:
          https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

          This page tells more about creating a PAT:
          https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
        required: false

jobs:
  determine-hooks:
    name: Determine skipped pre-commit hooks
    outputs:
      skipped-hooks: ${{ steps.hooks.outputs.skipped-hooks }}
      taplo-version: ${{ steps.taplo.outputs.taplo-version }}
    runs-on: ubuntu-22.04
    steps:
      - id: hooks
        uses: ComPWA/actions/get-skipped-pre-commit-hooks@v1
      - id: taplo
        uses: ComPWA/actions/get-pre-commit-taplo-version@v1

  pre-commit:
    name: Run local pre-commit hooks
    env:
      SKIP: taplo
    if: >-
      ${{ needs.determine-hooks.outputs.skipped-hooks != '' && needs.determine-hooks.outputs.skipped-hooks != 'taplo' }}
    needs: determine-hooks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ComPWA/actions/pip-install@v1
        with:
          editable: "yes"
          extras: sty
          python-version: ${{ inputs.python-version }}
      - name: Fetch pre-commit cache
        uses: actions/cache@v3
        with:
          key: |
            pre-commit-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-py${{ inputs.python-version }}
          path: ~/.cache/pre-commit/
      - if: needs.determine-hooks.outputs.skipped-hooks == 'ALL'
        run: pre-commit run --all-files --color always
      - if: needs.determine-hooks.outputs.skipped-hooks != 'ALL'
        name: Run pre-commit hooks that don't work on pre-commit.ci
        run: |-
          for hook in ${{ needs.determine-hooks.outputs.skipped-hooks }}; do
            pre-commit run $hook --all-files --color always
          done
      - id: diff
        if: always()
        name: Determine changed files
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "diff<<${delimiter}" >> $GITHUB_OUTPUT
          git diff --name-only | tee -a $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT
        shell: bash
      - if: always() && steps.diff.outputs.diff != ''
        uses: actions/upload-artifact@v3
        with:
          name: diff
          path: ${{ steps.diff.outputs.diff }}

  taplo:
    container:
      image: ghcr.io/compwa/mirrors-taplo:${{ needs.determine-hooks.outputs.taplo-version }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    if: needs.determine-hooks.outputs.taplo-version != ''
    name: Run taplo through pre-commit
    needs: determine-hooks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory $(pwd)
      - env:
          PRE_COMMIT_HOME: /root/.cache/pre-commit
        run: pre-commit run taplo --all-files --color always
      - id: diff
        if: always()
        name: Determine changed files
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "diff<<${delimiter}" >> $GITHUB_OUTPUT
          git diff --name-only | tee -a $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT
        shell: bash
      - if: always() && steps.diff.outputs.diff != ''
        uses: actions/upload-artifact@v3
        with:
          name: diff
          path: ${{ steps.diff.outputs.diff }}

  push:
    if: >-
      always() &&
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      contains(join(needs.*.result, ','), 'failure')
    name: Push changes
    needs:
      - pre-commit
      - taplo
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.token || secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v3
        with:
          name: diff
          path: .
      - if: always()
        name: Push changes
        run: |
          git diff --color
          if [[ $(git status -s) ]]; then
            git remote set-url origin https://x-access-token:${{ secrets.token }}@github.com/${{ github.repository }}
            git config user.name "GitHub"
            git config user.email "noreply@github.com"
            git add -A
            git commit -m "MAINT: implement updates from pre-commit hooks"
            git config pull.rebase true
            git pull origin ${{ github.head_ref }}
            git push origin HEAD:${{ github.head_ref }}
          fi
