on:
  workflow_call:

jobs:
  package-name:
    name: Determine package name
    runs-on: ubuntu-22.04
    outputs:
      name: ${{ steps.package-name.outputs.name }}
    steps:
      - id: package-name
        uses: ComPWA/actions/get-pypi-name@v1

  pypi:
    environment:
      name: PyPI
      url: https://pypi.org/p/${{ needs.package-name.outputs.name }}
    if: startsWith(github.ref, 'refs/tags')
    name: Publish to PyPI
    needs:
      - package-name
    permissions:
      id-token: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - run: pip install build
      - run: python3 -m build
      - uses: actions/upload-artifact@v4
        with:
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
