on:
  workflow_call:
    inputs:
      package-name:
        description: The name of the package to publish on PyPI
        required: true
        type: string

jobs:
  pypi:
    environment:
      name: pypi
      url: https://pypi.org/p/${{ github.event.inputs.package-name }}
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - run: pip install build
      - run: python3 -m build
      - uses: actions/upload-artifact@v4
        with:
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
