on:
  workflow_call:

jobs:
  push:
    name: Push to version branches
    if: startsWith(github.ref, 'refs/tags') && !github.event.release.prerelease
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git credentials
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Push to stable branch
        run: |
          git push origin HEAD:refs/heads/stable --force
      - name: Push to matching minor version branch
        env:
          TAG: ${{ github.ref_name }}
        run: |
          re='^(v?)([0-9]+)\.([0-9]+)\.[0-9]+'
          if [[ $TAG =~ $re ]]; then
            MINOR_VERSION_BRANCH="${BASH_REMATCH[1]}${BASH_REMATCH[2]}.${BASH_REMATCH[3]}.x"
            git push origin HEAD:refs/heads/$MINOR_VERSION_BRANCH --force
          fi
