name: Requirements

on: push

jobs:
  create-matrix:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        uses: ComPWA/actions/create-pytest-matrix@dev
        with:
          coverage-target: ampform
          macos-python-version: "3.7"

  run-matrix:
    needs: create-matrix
    runs-on: ubuntu-22.04
    steps:
      - run: echo '${{ needs.create-matrix.outputs.matrix }}'
